'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'../..'),deploy=process.env.ASTRA_DEPLOY_ROOT||path.join(root,'DEPLOY');
function context(extra={}){const window={setTimeout,clearTimeout,fetch:async()=>{throw Error('unexpected network')},HAIDIAN_SHADEMAP_CONFIG:{buildingMode:'osm',defaultResearchMode:'buildings'}};const c={window,document:{readyState:'loading',addEventListener(){},getElementById(){return null},querySelector(){return null}},console,Date,Map,Set,WeakMap,Math,Promise,performance,setTimeout,clearTimeout,AbortController,URL,URLSearchParams,Uint8Array,ArrayBuffer,TextEncoder,TextDecoder,Intl,Response,Headers,...extra};vm.createContext(c);return c;}
function load(c,file,edit=x=>x){vm.runInContext(edit(fs.readFileSync(path.join(deploy,file),'utf8')),c,{filename:file});}
function shadeContext(){const c=context();load(c,'vendor/building-vendor.js');c.window.ASTRABuildingVendor=c.ASTRABuildingVendor;load(c,'src/building-data-provider.js');load(c,'src/own-shade-renderer.js');load(c,'src/shademap-integration.js',s=>s.replace('  window.HaidianShade = {',`window.__core={solarPositionAt,buildingHeightMeta,prepareRouteModel,shadeStatusAt,getBuildings,
 setSnapshot(s){unifiedBuildingSnapshot=s},getSnapshot(){return unifiedBuildingSnapshot},setMode(m){state.mode=m},setDate(d){state.date=d},setFrame(f){ownShadeLayer={getFrame:()=>f}},setMap(m){mapRef=m},setProvider(p){globalBuildingProvider=p},setPrecision(fn){getPrecisionBuildings=fn},setCanopy(fn){findCanopyShadowEvidence=fn},setLegacy(f,b){lastBuildingFeatures=f;lastBuildingLoadedBounds=b;lastBuildingPipelineStatus={fetchComplete:true,coverageComplete:true}},legacy(){return {features:lastBuildingFeatures,bounds:lastBuildingLoadedBounds}},setVisual(v){state.visualProvider=v}};\n  window.HaidianShade = {`));c.window.__core.setVisual('own');return c;}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function deferred(){let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return {promise,resolve,reject};}
function bounds(b){return {...b,getSouth:()=>b.south,getWest:()=>b.west,getNorth:()=>b.north,getEast:()=>b.east,contains:p=>p.lat>=b.south&&p.lat<=b.north&&p.lng>=b.west&&p.lng<=b.east};}
function fakeMap(b={south:22.99,north:23.05,west:120.17,east:120.23}){const events=new Map(),canvases=[];return {canvases,getBounds:()=>bounds(b),getCenter:()=>({lat:(b.south+b.north)/2,lng:(b.west+b.east)/2}),getSize:()=>({x:800,y:600}),containerPointToLayerPoint:()=>({x:0,y:0}),latLngToContainerPoint:p=>({x:p.lng*1000,y:p.lat*1000}),getPane:()=>({appendChild:c=>canvases.push(c)}),on(e,fn){events.set(e,fn)},off(e){events.delete(e)},fire:e=>events.get(e)?.()};}
function fakeDocument(){return {createElement(){const ops=[];const ctx={ops,clearRect(){ops.push('clear')},drawImage(){ops.push('draw')},beginPath(){},moveTo(){},lineTo(){},closePath(){},fill(){ops.push('fill')}};return {style:{},width:0,height:0,getContext:()=>ctx,remove(){this.removed=true}};}};}
async function waitUntil(fn,timeout=1500){const t=performance.now();while(!fn()){if(performance.now()-t>timeout)throw Error('condition timeout');await delay(2);}}
function report(name,rows,extra={}){fs.mkdirSync(path.join(root,'evidence/dev37.9'),{recursive:true});fs.writeFileSync(path.join(root,'evidence/dev37.9',name+'.json'),JSON.stringify({executedUTC:new Date().toISOString(),deploy,checks:rows.length,rows,...extra},null,2));console.log('PASS',name,rows.length);}
module.exports={fs,path,vm,assert,root,deploy,context,load,shadeContext,delay,deferred,bounds,fakeMap,fakeDocument,waitUntil,report};
